version: '3'
services:
  mariadb:
    image: mariadb:10.4
    container_name: DRUPAL9_MARIADB
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./mariadb/.env
    volumes:
      - ./mariadb/db-data:/var/lib/mysql

  drupal:
    build:
      context: ./dockerfiles/
      dockerfile: drupal.dockerfile
    image: drupal9-with-composer
    container_name: DRUPAL9_DRUPAL
    depends_on:
      - mariadb
    restart: unless-stopped
    # volumes:
    #   - ./drupal/drupal-data:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: DRUPAL9_NGINX
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./drupal/drupal-data:/var/www/html
      - ./nginx/nginx-conf:/etc/nginx/conf.d

networks:
  default:
    external:
      name: DRUPAL9_DEFAULT

