version: '3'
services:
  # The Application
  laravel:
    build:
      context: ./docker/
      dockerfile: php-fpm.dockerfile
    container_name: LARAVEL_PHP
    working_dir: /var/www
    volumes:
      - ./src/:/var/www/

  # The Web Server
  nginx:
    build:
      context: ./docker/
      dockerfile: nginx.dockerfile
    container_name: LARAVEL_NGINX
    working_dir: /var/www
    volumes:
      - ./src/public:/var/www/public
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443